name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
          pip install nose coverage
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Run security scan with Bandit
        run: |
          pip install bandit
          bandit -r src

      - name: Run dependency check with safety
        run: |
          pip install safety
          safety check

      - name: Run end-to-end tests with Pytest
        run: |
          pip install pytest
          pytest tests_e2e/

